name: Build App only on dev Branch

on:
    push:
        branches: [dev]
env:
    PNPM_STORE_PATH: C:\Users\runneradmin\AppData\Local\pnpm\store\v3

jobs:
    buildApp:
        name: Build Application
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure pnpm
              uses: pnpm/action-setup@v4

            - name: install frontend dependencies
              run: pnpm install

            - name: Build the app
              id: build
              uses: tauri-apps/tauri-action@v0

              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
                  # 使用之前配置的私钥
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  # 使用之前配置的私钥密码
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
              with:
                  includeDebug: true
                  includeUpdaterJson: true
                  updaterJsonPreferNsis: true
                  tagName: ${{ github.ref_name }}
                  releaseBody: "See the assets to download and install this version."
                  releaseDraft: false
                  prerelease: false
                  projectPath: ./apps/app
                  tauriScript: pnpm
