name: Dev release

on:
  push: branches:[Dev]

env:

jobs:
  init:
    name: Env Init
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup nodejs 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          
      - name: install pnpm
        run: npm i pnpm -g


  build:
    name: Build
    needs: init

  publish:
    name: Publish
    needs: [init, build]
