name: Dev release

on:
  push:
    branches: [Dev]

jobs:
  runs-on: windows-latest
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install
    # Build Tauri application
    - name: Build Tauri application
      working-directory:
      run: pnpm tauri build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output # Artifact 名称
        path: src-tauri/target/release/bundle/msi/*.msi
