name: Dev release

on:
  push:
    branches: [Dev]

jobs:
  init:
    name: Release DevVersion
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 需要获取完整历史记录以进行 diff 比较

      - name: Check for package.json changes
        id: check-package-json
        shell: pwsh
        run: |
          $changedFiles = git diff --name-only HEAD^ HEAD
          if ($changedFiles -match "package.json") {
            Write-Host "package.json has changed"
            echo "::set-output name=changed::true"
          } else {
            Write-Host "package.json has not changed"
            echo "::set-output name=changed::false"
          }

      - name: Restore pnpm cache if package.json hasn't changed
        if: steps.check-package-json.outputs.changed == 'false'
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        if: steps.check-package-json.outputs.changed == 'true' || steps.check-package-json.outputs.changed == 'false' && steps.restore-cache.outputs.found == 'false'

        run: pnpm install
        working-directory: .

      - name: Build Tauri application
        shell: pwsh
        run: |
          npx tauri build
        working-directory: .
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output # Artifact 名称
          path: src-tauri/target/release/bundle/msi/*.msi
