name: Rust and Node.js CI with Tauri

on:
  push:
    branches: [Dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # 检出仓库代码

    - name: Set up Rust
      uses: actions-rs/toolchain@v1 # 设置Rust工具链
      with:
        toolchain: stable # 使用稳定版Rust工具链
        profile: minimal # 使用最小化配置文件
        override: true # 覆盖任何现有的Rust工具链设置

    - name: Cache Yarn Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: {{ runner.os }}-yarn-{{ hashFiles('**/yarn.lock') }

    - name: Restore Yarn Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: {{ runner.os }}-yarn-{{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          {{ runner.os }}-yarn-{{ runner.os }}-

    - name: Install Dependencies
      run: yarn install


    # Build Tauri application
    - name: Build Tauri application
      working-directory: 
      run: yarn  tauri build


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output  # Artifact 名称
        path: src-tauri/target/release/bundle/msi

    - name: Save Yarn Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: {{ runner.os }}-yarn-{{ hashFiles('**/yarn.lock') }}
        save-key: {{ runner.os }}-yarn-{{ hashFiles('**/yarn.lock') }}