name: Rust and Node.js CI with Tauri

on:
  push:
    branches: [Dev]

env:

jobs:
  runs-on: windows-latest

  envsetup:
    - name: setup env
    - steps:
        - uses: actions/checkout@v3

        - name: Set Node.js 20.x
          uses: actions/setup-node@v3
          with:
            node-version: 20.x

        # install pnpm
        - name: install pnpm
          run: npm i pnpm -g

        # install node_modules
        - name: Run install
          with:
            cmd: pnpm install # will run `yarn install` command

  build:
    - needs: envsetup
    - name: build application
    - steps:
        # Build Tauri application
        - name: Build Tauri application
          working-directory:
          run: pnpm tauri build

  publish:
    - needs: build
    - name: publish to release
    - steps:
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: build-output # Artifact 名称
            path: src-tauri/target/release/bundle/msi/*.msi
