name: Rust and Node.js CI with Tauri

on:
  push:
    branches: [Dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # 检出仓库代码

    - name: Set up Rust
      uses: actions-rs/toolchain@v1 # 设置Rust工具链
      with:
        toolchain: stable # 使用稳定版Rust工具链
        profile: minimal # 使用最小化配置文件
        override: true # 覆盖任何现有的Rust工具链设置

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Install Node.js version 20

    # Enable corepack (Yarn and pnpm support)
    - name: Enable corepack
      run: corepack enable

    # Install Node.js dependencies with Yarn
    - name: Install Node.js dependencies
      run: yarn --frozen-lockfile

    # Install Rust dependencies in /tauri-src directory
    - name: Install Rust dependencies
      working-directory: src-tauri
      run: |
        cargo install --path .
        # If you have a specific command to install dependencies, replace the above line with it.

    # Build Tauri application
    - name: Build Tauri application
      working-directory: 
      run: tauri build
